CREATE TABLE booking (
	bookingid bigint auto_increment NOT NULL,
	bibid integer NOT NULL,
	book_dt date NOT NULL,
	due_dt date NOT NULL,
	out_histid bigint NULL,
	out_dt datetime NULL,
	ret_histid bigint NULL,
	ret_dt datetime NULL,
	create_dt datetime NOT NULL,
	last_change_dt datetime NOT NULL,
	last_change_userid integer NOT NULL,
	PRIMARY KEY (bookingid),
	KEY `bibid_idx` (`bibid`),
	KEY `due_dt_idx` (`due_dt`),
	KEY `book_dt_idx` (`book_dt`),
	KEY `out_histid_idx` (`out_histid`),
	KEY `out_dt_idx` (`out_dt`),
	KEY `ret_histid_idx` (`ret_histid`),
	KEY `ret_dt_idx` (`ret_dt`)
);
