insert into %prfx%state_dm values ('AL','Alabama','N');
insert into %prfx%state_dm values ('AK','Alaska','N');
insert into %prfx%state_dm values ('AZ','Arizona','N');
insert into %prfx%state_dm values ('AR','Arkansas','N');
insert into %prfx%state_dm values ('CA','California','N');
insert into %prfx%state_dm values ('CO','Colorado','N');
insert into %prfx%state_dm values ('CT','Connecticut','N');
insert into %prfx%state_dm values ('DE','Delaware','N');
insert into %prfx%state_dm values ('DC','Dist. of Columbia','N');
insert into %prfx%state_dm values ('FL','Florida','N');
insert into %prfx%state_dm values ('GA','Georgia','N');
insert into %prfx%state_dm values ('GU','Guam','N');
insert into %prfx%state_dm values ('HI','Hawaii','N');
insert into %prfx%state_dm values ('ID','Idaho','N');
insert into %prfx%state_dm values ('IL','Illinois','N');
insert into %prfx%state_dm values ('IN','Indiana','N');
insert into %prfx%state_dm values ('IA','Iowa','N');
insert into %prfx%state_dm values ('KS','Kansas','N');
insert into %prfx%state_dm values ('KY','Kentucky','N');
insert into %prfx%state_dm values ('LA','Louisiana','N');
insert into %prfx%state_dm values ('ME','Maine','N');
insert into %prfx%state_dm values ('MD','Maryland','N');
insert into %prfx%state_dm values ('MA','Massachusetts','N');
insert into %prfx%state_dm values ('MI','Michigan','N');
insert into %prfx%state_dm values ('MN','Minnesota','N');
insert into %prfx%state_dm values ('MS','Mississippi','N');
insert into %prfx%state_dm values ('MO','Missouri','N');
insert into %prfx%state_dm values ('MT','Montana','N');
insert into %prfx%state_dm values ('NE','Nebraska','N');
insert into %prfx%state_dm values ('NV','Nevada','N');
insert into %prfx%state_dm values ('NH','New Hampshire','N');
insert into %prfx%state_dm values ('NJ','New Jersey','N');
insert into %prfx%state_dm values ('NM','New Mexico','N');
insert into %prfx%state_dm values ('NY','New York','N');
insert into %prfx%state_dm values ('NC','North Carolina','N');
insert into %prfx%state_dm values ('ND','North Dakota','N');
insert into %prfx%state_dm values ('OH','Ohio','N');
insert into %prfx%state_dm values ('OK','Oklahoma','N');
insert into %prfx%state_dm values ('OR','Oregon','N');
insert into %prfx%state_dm values ('PA','Pennsylvania','N');
insert into %prfx%state_dm values ('PR','Puerto Rico','N');
insert into %prfx%state_dm values ('RI','Rhode Island','N');
insert into %prfx%state_dm values ('SC','South Carolina','N');
insert into %prfx%state_dm values ('SD','South Dakota','N');
insert into %prfx%state_dm values ('TN','Tennessee','N');
insert into %prfx%state_dm values ('TX','Texas','N');
insert into %prfx%state_dm values ('UT','Utah','N');
insert into %prfx%state_dm values ('VT','Vermont','N');
insert into %prfx%state_dm values ('VA','Virginia','N');
insert into %prfx%state_dm values ('VI','Virgin Islands','N');
insert into %prfx%state_dm values ('WA','Washington','N');
insert into %prfx%state_dm values ('WV','West Virginia','N');
insert into %prfx%state_dm values ('WI','Wisconsin','N');
insert into %prfx%state_dm values ('WY','Wyoming','N');
